### ISSUE TITLE
Restic backups - can fail on lost+found directory 

### ISSUE THREAD

**Issue by tesshuflower** [backube/volsync#1033]
**Describe the bug**

Restic backups may fail due to lost+found directory created for ext4 filesystems.  Should exclude this dir from restic backups.

**Steps to reproduce**

**Expected behavior**

**Actual results**

**Additional context**

**Comment by tesshuflower** [comment]
Reported by [@erenfro](https://github.com/erenfro) .  

Interestingly, we do have ext4 in use in e2e tests that run on OpenShift in AWS, however they haven't caught this.  My best guess is it's because in OpenShift fsGroup is set automatically and lost+found ends up being readable by the group. 

[@erenfro](https://github.com/erenfro) Do you currently set fsGroup in your `spec.restic.moverSecurityContext`?

**Comment by erenfro** [comment]
I don't generally set that, but despite that, lost+found technically should always ever be root:root owned, as this is an innate part of the filesystem design itself. It simply _should not_ be included in the backup regardless of what permissions it has.

**Comment by erenfro** [comment]
And actually, often times, yes, it's actually set in my moverSecurityContext template I use.

**Comment by tesshuflower** [comment]
> And actually, by default, yes, it's actually set in my moverSecurityContext template I use.

thx for the confirmation

**Comment by erenfro** [comment]
For reference, I use this setup for my VolSync, in a templated fashion:
Template: https://github.com/erenfro/homelab-flux/tree/main/kubernetes/templates/volsync
Application: https://github.com/erenfro/homelab-flux/tree/main/kubernetes/apps/selfhosted/mealie
