### ISSUE TITLE
unknown command "start-replication" for "kubectl-volsync"

### ISSUE THREAD

**Issue by oranichu** [backube/volsync#114]
**Describe the bug**
Not sure if its a bug or outdated documentation but I'm trying the [Rsync Database Cross-Cluster Plugin Example](https://volsync.readthedocs.io/en/latest/usage/rsync/multi_context_sync_cli.html), and to perform this example I need to run the `kubectl volsync start-replication` command which returns `Error: unknown command "start-replication" for "kubectl-volsync`

Tried to look for an alternative but couldn't find it, this is after installing the CLI on my MacBook pro.
When I try to `make cli` on one of my Ubuntu machines I get this error 
`orannaho@wg2-w1:~/volsync$ make cli
/home/orannaho/volsync/bin/golangci-lint run ./...
panic: load embedded ruleguard rules: rules/rules.go:438: StringWriter is not found in io

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.9()
	github.com/go-critic/go-critic@v0.6.1/checkers/checkers.go:58 +0x4b4
Makefile:98: recipe for target 'lint' failed
make: *** [lint] Error 2`

that I also couldn't find a solution to.

**Steps to reproduce**
`kubectl volsync start-replication` 

**Expected behavior**
suppose to start replication just like in the example 

**Actual results**
`Error: unknown command "start-replication" for "kubectl-volsync`**Additional context**

Thanks.

**Comment by JohnStrunk** [comment]
I'm not sure about the issue w/ the linter, but the issue w/ `start-replication` is that we're in the process of reworking the CLI.

The docs describe the old CLI, which you can build via:
```console
$ go build -o kubectl-volsync-old ./cmd/volsync/volsync.go
$ ./kubectl-volsync-old --help
VolSync is a command line tool for a volsync operator running in a Kubernetes cluster. VolSync asynchronously replicates Kubernetes persistent volumes between clusters or namespaces using rsync, rclone, or restic. VolSync uses a ReplicationDestination and a ReplicationSource to replicate a volume. Data will be synced according to the configured sync schedule.

Usage:
  volsync [flags]
  volsync [command]

Available Commands:
  completion           generate the autocompletion script for the specified shell
  continue-replication remove a manual trigger from a volsync replication source to resume replications.
  help                 Help about any command
  remove-replication   Remove a volsync replication and its resources.
  set-replication      Set and pause a volsync replication and ensure a destination PVC with synced data.
  start-replication    Start a volsync replication for  a persistent volume.

Flags:
  -h, --help             help for volsync
      --loglevel int32   Set the level of log output (0-10)
  -v, --version          version for volsync

Use "volsync [command] --help" for more information about a command.
```

The new CLI isn't usable yet.

**Comment by oranichu** [comment]
Hey John!
This worked for me as now I was able to use the kubectl-volsync-old commands as instructed in the tutorial.
Yet I wasn't still able to successfully replicate data across different clusters (I tried from a kind cluster to a minikube cluster, and from two different kind clusters), the start-replication command seems to finish successfully yet the set-replication always time-out.

I was wondering if I can get help with that, should I post everything here ? (my setup and tries) or in the discussion section?
Not sure where to put this 😅

Thanks!

**Comment by JohnStrunk** [comment]
My first guess is a networking problem, given kind & minikube... but let's see...

The nice thing about the CLI is that all it does is manipulate VolSync's CRs, so we should be able to figure out the issue looking at the objects in cluster.

Let's start w/ a kubectl describe of:
- pods, pvcs, volumesnapshots, replicationsource, replicationdestination objects in both the source and destination namespace.

If it's a networking issue, we'd expect to see that the destination pod has been running for a long time (waiting for a transfer), and the source pod/job is restarting periodically trying to connect.

Other sources of problems are incorrect settings for storage such as:
- Using CopyMethod: Clone w/ a CSI driver that doesn't support clone
- Using CopyMethod: Snapshot and not having the VolumeSnapshotClass set up properly (not default or not specified in the VolSync CRs)
Storage problems typically look like unbound PVCs or VolumeSnapshots

**Comment by oranichu** [comment]
If i'm trying to use LoadBalancer as the service type (like in the example) after start-replication I'm getting 
``` Waiting for ReplicationDestination dest-destination RSync address to populate```

If I'm using ClusterIP I'm getting the same issue you described.

So yes, I reckon it is a networking issue as well.
Is there a possibility of exposing the ReplicationDestination.status.rsync.adress (I'm guessing this is failing here when it's trying to connect to this IP address)?

**Comment by JohnStrunk** [comment]
When you're running w/ kind, you'd need to add something like https://kind.sigs.k8s.io/docs/user/loadbalancer/ in order to make use of the LoadBalancer Service type (caveat: I've never tried LBs w/ kind). ClusterIP is what I use w/ kind.
Since ClusterIP won't give you an externally accessible address, you need to expose it yourself via `kubectl port-forward`. This will bind a port on your local machine and forward it to the Service. You should be able to have the RS connect to this forwarded port from your other cluster.
I'd expect you'll need to use `--address=0.0.0.0` w/ port forward so that it binds to all the machine IPs.

Something like:
- Create RD using ClusterIP
- Wait for address and key to populate in the RD.status
- Copy the key Secret across
- Locate the corresponding Service in the RD's namespace
- In a separate terminal, `kubectl port-forward --address 0.0.0.0 8000:22 -n <rd-namespace> svc/<svcname>`
- Create the RS and use your local machine's IP in the address field and 8000 in the port field.

The CLI doesn't support this sort of configuration, so you'll need to set up the CRs yourself.

**Comment by oranichu** [comment]
Thanks, I'll continue from here and keep posted for any interesting results!
