### ISSUE TITLE
Adjust docs to encourage specifying StorageClass and VSC 

### ISSUE THREAD

**Issue by JohnStrunk** [backube/volsync#128]
**Describe the feature you'd like to have.**
Right now, the docs are written in a way that encourages not directly specifying the StorageClassName or VolumeSnapshotClassName. When omitted, this relies on having properly configured defaults in the cluster for both of these (and that they are compatible w/ the volume being replicated.

**What is the value to the end user? (why is it a priority?)**
Users seem to run into problems when relying on the cluster defaults

**How will we know we have a good solution? (acceptance criteria)**
The docs/examples should be reworked to encourage users to directly specify SC & VSC when they are creating RS & RD objects.

**Additional context**

cc: @netzzer

**Comment by netzzer** [comment]
This will make it easier for users of volsync to 1) know that a StorageClass (SC) with a CSI snapshot/clone capable provisioner needs to be specified in the RS and RD; 2) know that a VolumeSnapshotClass (VSC) that matches SC provisioner either needs to be created or identified if already created (installing ODF as of v4.6+ results in 2 VSC, one for cephfs and one for cephrbd). Also, if there is a need to created RS and RD for RWO and RWX volumes, for example cephfs and cephrbd storage type, then a default SC and VSC cannot be used given there can only be one default SC/VSC per OCP cluster.

**Comment by JohnStrunk** [comment]
Doc changes were in #136 
/close
