### ISSUE TITLE
Introduce max simultanous src/dest actions

### ISSUE THREAD

**Issue by PrivatePuffin** [backube/volsync#1423]
**Describe the feature you'd like to have.**
I would like settings to adjust the maximum simultanous dest and/or src actions ran by volsync.

**What is the value to the end user? (why is it a priority?)**
There are cases where a lot of volumes need to be send or received (backup for example) and not all storage backends like too many snapshotting actions for example.

By being able to volsync-wide limit the amount of actions, users with high demands would adjust accordingly.

**How will we know we have a good solution? (acceptance criteria)**

When users with high demands can adjust this, without it affecting current users or any defaults.

**Additional context**

**Comment by tesshuflower** [comment]
I don't think VolSync wants to start keeping track of this - currently there is no global view of all replicationsource/dests in the VolSync controller.

I'd suggest you could try spreading out the schedules, or looking at something like resource quotas for the resources (volumesnapshots?) that you are having issues with: https://kubernetes.io/docs/concepts/policy/resource-quotas/#object-count-quota

**Comment by PrivatePuffin** [comment]
Its not personally an issue of me personally.
But something I came across when discussing deployments with others.

The deployment in question was running 3000+ pvc, at those rates, spreading it out is not going to cut it (much)

---

I doubt the Volsync pods or operator are going behave well when quotas are being put on volume snapshots, or is it?

**Comment by tesshuflower** [comment]
I guess I'm not convinced volsync should be the one limiting this atm.  Is the issue the CSI storage driver itself which is not able to handle the simultaneous snapshot requests?  If the external snapshotter or storage driver itself is not limiting simultaneous rates of creating volumesnapshots, not sure volsync should be the one to do it.  VolSync does many other operations as well (and may or may not even take a snapshot), so all of that would need to be considered if we decided to try and put some sort of global limits.

I think you're right if you put a quota on number of volumesnapshots, volsync would repeatedly try to create them - I guess I was thinking someone could put a quota on a number of replicationsource or destination objects in a namespace but sounds like this is not going to really work in your scenario.
