### ISSUE TITLE
volsync migration: support for cluster to cluster migration

### ISSUE THREAD

**Issue by vh05** [backube/volsync#150]
**Describe the feature you'd like to have.**

Users look to migrate from one k8s cluster to other because of many reasons. ex: ocs(glusterfs) to odf (cephfs). Volsync migration utility can be extended to provision such feature.

**What is the value to the end user? (why is it a priority?)**

Migration across clusters is much needed ask and users tend to move from one cluster to other (cloud to cloud as well)

@JohnStrunk Please review the feature

**Comment by JohnStrunk** [comment]
I think this is handled by the cli's `replication` set of sub-commands. Something like:
```console
$ kubectl volsync replication create ...
$ kubectl volsync replication set-source --copymethod Direct ... # source is the PVC in the old cluster
$ kubectl volsync replication set-destination --copymethod Direct --storageclass newsc ... # destination is the new cluster
$ kubectl volsync replication sync  # actually transfer the data
$ kubectl volsync replication delete  # clean up
```

Is there more that you believe we should be doing?

**Comment by v-harihar** [comment]
>  $ kubectl volsync replication set-source --copymethod Direct ... # source is the PVC in the old cluster
> $ kubectl volsync replication set-destination --copymethod Direct --storageclass newsc ... # destination is the new cluster

I was thinking to bring this while filing this issue. 

What I think is, the above mentioned commands `set-source` and `set-destination` should also be part of migration with default `--copymethod Direct` (or else (I prefer) the functionality of `set-source` and `set-destination` can be assumed internally as part of `migration create` command and exclude `set-source` and `set-destination` sub commands). If `migration` subcommand can have this, then the user will be more sure what the command is doing and refers migration subcommand for any of the migration operation. 

I understand the `replication subcommand` serves the same purpose but doing it as part of `migration subcommand` does make more sense.

Please correct me if wrong.
