### ISSUE TITLE
volsync migration: support for different volume types on ODF 

### ISSUE THREAD

**Issue by v-harihar** [backube/volsync#152]
This is not a feature request for volsync migration but to ODF. The intention is to highlight what we are missing in the current `replicationdestination` cluster. We can treat this as tracker if in case we open up the issue with ODF. 

**Describe the feature you'd like to have.**

Users choose cetain volume type (considering gluster) based on cost, performance, usage. The destination cluster should match users requirements, build the destination cluster and migrate the data. So that cost, performance not altered.

**What is the value to the end user? (why is it a priority?)**

Users will find best value after migration.

**Comment by JohnStrunk** [comment]
I don't think there is anything for VolSync to do here
