### ISSUE TITLE
Evaluate syncthing as a mover

### ISSUE THREAD

**Issue by JohnStrunk** [backube/volsync#19]
**Describe the feature you'd like to have.**
We should see if there is any benefit to adding [Syncthing](https://syncthing.net/) as an additional data mover.

**What is the value to the end user? (why is it a priority?)**

**How will we know we have a good solution? (acceptance criteria)**

**Additional context**
I don't currently have an opinion on this (or know anything about syncthing). I'm just recording it so it doesn't get lost.

**Comment by RobotSail** [comment]
Pull-request #134 should close this issue
