### ISSUE TITLE
CI Flake: [It] Ensure lastSyncDuration is set at the end of an iteration

### ISSUE THREAD

**Issue by tesshuflower** [backube/volsync#213]
**Describe the bug**

```
ReplicationSource when a copyMethod of Snapshot is specified When snapshot is bound correctly [It] Ensure lastSyncDuration is set at the end of an iteration 
/go/src/github.com/backube/volsync/controllers/replicationsource_test.go:353
  Expected
      <*v1.Time | 0xc001acac90>: {
          Time: 2022-05-06T20:36:00Z,
      }
  to be nil

 /go/src/github.com/backube/volsync/controllers/replicationsource_test.go:380
```

**Steps to reproduce**

**Expected behavior**

**Actual results**

**Additional context**

Found in #212 

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/backube_volsync/212/pull-ci-backube-volsync-main-unit/1522674364502249472

**Comment by JohnStrunk** [comment]
I just saw this failure (after 192 attempts :cry:)
Using main @ d314986 (current as of this morning)

Command I'm using:
```
$ KUBEBUILDER_ASSETS="/home/jstrunk/.local/share/kubebuilder-envtest/k8s/1.23.3-linux-amd64" /home/jstrunk/src/backube/volsync/bin/ginkgo -randomizeAllSpecs -untilItFails -slowSpecThreshold 30 -focus lastSyncDuration ./controllers
```

**Comment by tesshuflower** [comment]
Thanks for that! When I ran with -untilItFails it would always eventually fail with the testenv somewhere - running better now.  Love the message 😂

```
All tests passed...
Will keep running them until they fail.
This was attempt #173
No, seriously... you can probably stop now.
```

**Comment by tesshuflower** [comment]
I actually haven't been able to reproduce, just left it running all afternoon and it's now around ~attempt #1123...

I actually think my best guess as to why this occurred is that this particular test was slow and most likely the cleanup completed before doing the check in the Eventually here:  https://github.com/backube/volsync/blob/main/controllers/replicationsource_test.go#L373-L376.   So lastSyncStartTime was set (as expected) but we missed it clearing out lastSyncStartTime because possibly the cleanup already completed and it transitioned to synchronizing again.  

However, the schedule is set to every 4 mins ("*/4 * * * *") so really this shouldn't have happened?  I'm a bit confused as to what's going on, but could be a peculiarity of the initial schedule I'm guessing.

I tried adding some debug logging in the test and was able to generate a run like this:

ReplicationSource before the job was marked as successful:

```
...
   "spec": {
      "sourcePVC": "thesource",
      "trigger": {
        "schedule": "*/4 * * * *"
      },
      "rsync": {
        "copyMethod": "Snapshot"
      }
    },
    "status": {
      "lastSyncStartTime": "2022-05-12T19:59:49Z",
      "rsync": {
        "sshKeys": "volsync-rsync-src-dest-instance",
        "address": "10.0.0.64"
      },
      "conditions": [
        {
          "type": "Synchronizing",
          "status": "True",
          "lastTransitionTime": "2022-05-12T19:59:49Z",
          "reason": "SyncInProgress",
          "message": "Synchronization in-progress"
        }
      ]
    }
```

Then I log the RS after the check to make sure lastSyncDuration is filled in:
```
...
  "spec": {
      "sourcePVC": "thesource",
      "trigger": {
        "schedule": "*/4 * * * *"
      },
      "rsync": {
        "copyMethod": "Snapshot"
      }
    },
    "status": {
      "lastSyncTime": "2022-05-12T19:59:51Z",
      "lastSyncDuration": "2.622837s",
      "nextSyncTime": "2022-05-12T20:00:00Z",
      "rsync": {
        "sshKeys": "volsync-rsync-src-dest-instance",
        "address": "10.0.0.64"
      },
      "conditions": [
        {
          "type": "Synchronizing",
          "status": "False",
          "lastTransitionTime": "2022-05-12T19:59:51Z",
          "reason": "WaitingForSchedule",
          "message": "Waiting for next scheduled synchronization"
        }
      ]
    }
```

You can see the next sync time is actually almost immediately.

I think the cron schedule is every 4 mins, but this basically divides the hour into 4 min segments, and probably starts at 0 for every hour? So if we initially start at 19:59 even with an every 4 min cycle our next start time may end up being 20:00.

@JohnStrunk sorry for the really long comment, but interested for your take on this - the short version is, this may just be a quirk of running the initial schedule - if the test happened to start right before the end of the hour, it's possible the next schedule will be almost immediately, and so it's possible for it to transition to the next sync cycle (and therefore set the `LastSyncStartTime` again before the test catches it).  If so, I'm not sure it's actually any code problem, more of an issue with the test.

If this is really how the cron scheduling works, it might be an argument for adding something like that skew parameter (as optional) that Ryan Cook suggested.

**Comment by JohnStrunk** [comment]
I think you're probably correct about the cause... a new iteration starting immediately. The "*/4" syntax starts an iteration when minutes mod 4 == 0, so it's entirely possible.
There used to be other CI flakes for the same reason, but I changed those to be "0 0 1 1 *" (Jan 1 at midnight) to reduce the chance of flakes w/o getting rid of the schedule entirely. We could do that here.

Another set of options:
- Get rid of this test. It should be covered in the statemachine tests (if not, it should be), so running the full controller may not be necessary.
- Switch the schedule to manual so it'll never re-trigger (I haven't looked at the other tests in the Describe block and whether it'd be a problem for them)

**Comment by tesshuflower** [comment]
thanks John - I've gone with the manual trigger option as it doesn't seem like any of those tests are relying on the schedule (they just are testing 1 synchronization).
