### ISSUE TITLE
[Ramen Integration] Ramen would like to be able to identify VolSync temporary PVCs via label or annotation

### ISSUE THREAD

**Issue by tesshuflower** [backube/volsync#239]
**Describe the feature you'd like to have.**
Ramen is using VolSync to replicate PVCs (usually via a label selector) but there is a scenario where they may find all PVCs in a namespace.

Ramen could get into a loop in this scenario where they keep finding temporary PVCs created by VolSync and attempt to protect them as well.  

Ideally if VolSync created PVCs had a label or annotation on them (on the ReplicationSource side, but it may be useful on destination as well?) then they could be excluded from Ramen's query.

If we are creating this label/annotation, it is probably also useful for VolSync itself to check these, and refuse to replicate these PVCs.

**What is the value to the end user? (why is it a priority?)**
- Other users may find it useful to identify PVCs created by VolSync as well.
- Prevent VolSync from getting into any loops of trying to replicate PVCs created by other ReplicationSource resources.

**How will we know we have a good solution? (acceptance criteria)**

**Additional context**

To Investigate:
- Can labels be used in a "not matching" query? If so, it may be preferable to use a label vs an annotation.

**Comment by JohnStrunk** [comment]
While working on #248 I ran into an issue where I need to be able to exclude volsync mover pods from the affinity detection.
We should probably expand this item to include labeling all resources that volsync creates/owns.

**Comment by tesshuflower** [comment]
Fixed by https://github.com/backube/volsync/pull/248

volsync pods (and other created resources) should now get the following label:

```
app.kubernetes.io/created-by: "volsync"
```
