### ISSUE TITLE
Investigate whether AUDIT_WRITE can be removed from rsync mover pod

### ISSUE THREAD

**Issue by tesshuflower** [backube/volsync#257]
**Describe the feature you'd like to have.**
Permissions will start to be an issue with Pod Security Admission updates coming in Kubernetes (which for example will be on in OCP 4.11, but perhaps only enforced in OCP 4.12?).

`sshd` in the rsync mover pod requires `AUDIT_WRITE` capability - we think this is mostly to be able to write audit logs (rsync doesn't seem to have any option to disable writing these).

Can we remove the AUDIT_WRITE capability from the rsync mover pod by mounting an `emptyDir` volume and mounting it to where rsync writes its audit logs?

**How will we know we have a good solution? (acceptance criteria)**
- AUDIT_WRITE capability no longer required for rsync mover pod

**Comment by tesshuflower** [comment]
Unfortunately it looks like hacks to mount an emptyDir volume are not working - audit write is happening at the host level rather than the container, so it seems this workaround will not work.

**Comment by JohnStrunk** [comment]
/close
audit write will be removed in the new rsync/stunnel mover
