### ISSUE TITLE
CI Flake: Wrap `client.Create()` calls

### ISSUE THREAD

**Issue by JohnStrunk** [backube/volsync#267]
The below needs to be wrapped to ensure the object is visible:
https://github.com/backube/volsync/blob/1d00a461beb074263a394a1bb89d25096cd8dc10/controllers/mover/rsync/rsync_test.go#L1143

```
Rsync as a destination when used as destination SSH keys are handled properly When ssh keys are provided When provided secret exists but missing fields [It] Mover should fail to ensureSecrets 
/home/runner/work/volsync/volsync/controllers/mover/rsync/rsync_test.go:1148
Expected
      <string>: Secret "test-dest-keys-bad" not found
  to contain substring
      <string>: fields
  /home/runner/work/volsync/volsync/controllers/mover/rsync/rsync_test.go:1152
```

We should probably create a helper method to replace the `client.Create()` call to handle these cases, and do a search/replace.

**Comment by tesshuflower** [comment]
/assign @tesshuflower 

I can take a look at this - I have another similar issue: https://github.com/backube/volsync/issues/291. Where a status().Update() is also not getting picked up by the cache sometimes - maybe this can be wrapped as well.

**Comment by tesshuflower** [comment]
/close

closed by https://github.com/backube/volsync/pull/316
