### ISSUE TITLE
Restic mover stuck in pending, can't attach PVC and PVC not bound

### ISSUE THREAD

**Issue by JohnStrunk** [backube/volsync#361]
**Describe the bug**
- The Restic mover is stuck in pending
- The cache PVC is not bound and waiting for 1st consumer
- The cache PVC can't be attached because it's not bound

**Steps to reproduce**
- Restic mover
  - CopyMethod: Direct
  - Source PVC is RWO
- An existing pod is using the source PVC

**Expected behavior**
The mover pod should start

**Actual results**

**Additional context**
https://issues.redhat.com/browse/OADP-647

This appears to be due to the affinity setter which directly sets the nodeName in the podspec. This seems to completely bypass the scheduler, and subsequently bypass the volume provisioning step, leaving us w/ an unbound PVC that can't be attached.
This will only happen on the 1st invocation of the mover if an existing pod is using the sourcePVC (triggering the affinity setter). On subsequent invocations, the PVC will already be bound, so there should be no scheduling problems.

**Comment by JohnStrunk** [comment]
This will need a backport to release-0.5 branch

**Comment by tesshuflower** [comment]
/close

Fix merged into main and also cherry-picked into `release-0.5`.
