### ISSUE TITLE
Ensure auto-generated files are up-to-date vi GH actions

### ISSUE THREAD

**Issue by JohnStrunk** [backube/volsync#481]
**Describe the feature you'd like to have.**
There should be a check in the GH workflow that makes sure various auto-generated files are up-to-date w/ their corresponding sources.

For example, we already have a check that verifies `go.mod`  and `go.sum`

Other items to add:
- Scorecard config yaml (`make custom-scorecard-tests-generate-config`) [mentioned here](https://github.com/backube/volsync/pull/480#pullrequestreview-1160155424)
- The deepcopy and CRD files via `manifests` and `generate` targets
- The CSV via `bundle` target

**What is the value to the end user? (why is it a priority?)**

**How will we know we have a good solution? (acceptance criteria)**

**Additional context**
My thought is that we can run a `make` on the above, then check if the associated files are modified and error the CI.
One concern is that different versions of the utilities can cause slight differences in the files (e.g., whitespace). I'm not sure how to handle that robustly.

**Comment by tesshuflower** [comment]
We could potentially use `git diff -b` (aka ` --ignore-space-change`) to ignore whitespace changes in those generated files?

**Comment by tesshuflower** [comment]
I could take a look at this

/assign
