### ISSUE TITLE
cli should be usable w/o a config file

### ISSUE THREAD

**Issue by JohnStrunk** [backube/volsync#49]
**Describe the feature you'd like to have.**
It should be possible to use the cli w/o having a config file.

Currently:
```console
$ kubectl volsync help
error: Config File "config.yaml" Not Found in "[/home/jstrunk/.volsyncconfig]"
```

**What is the value to the end user? (why is it a priority?)**

**How will we know we have a good solution? (acceptance criteria)**
- A missing config file should be treated as empty
- ~It should be possible to provide an alternate location for the config file~ This exists `--config <filename`
- It should be possible to use the cli in full w/o a config file (everything via cli parameters)

**Additional context**
Related to #22, #10

**Comment by sallyom** [comment]
@JohnStrunk I only noticed this the other day, **this is a bug** not intended behavior,  thank you!
