### ISSUE TITLE
CI: OpenShift detection in unit tests

### ISSUE THREAD

**Issue by JohnStrunk** [backube/volsync#514]
**Describe the bug**
We're getting fairly regular, though intermittent, failures of the following test in CI.

```
• Failure [0.007 seconds]
A cluster w/o StorageContextConstraints [It] should NOT be detected as OpenShift 
/home/runner/work/volsync/volsync/controllers/platform/properties_test.go:43

  Expected
      <bool>: true
  to be false

  /home/runner/work/volsync/volsync/controllers/platform/properties_test.go:46
```

**Steps to reproduce**

**Expected behavior**

**Actual results**

**Additional context**
This seems to be a case of system state leaking between tests.

**Comment by tesshuflower** [comment]
/assign @tesshuflower 

I was experiencing this before and I guess my fixes to cleanup CRDs at the end of tests didn't fix it entirely.  I think perhaps one solution is to cleanup the CRD itself at the end of each test and also wait for it to be gone.
