### ISSUE TITLE
cli options should be more clear

### ISSUE THREAD

**Issue by sallyom** [backube/volsync#52]
The current CLI options are confusing to anyone trying to develop on the CLI.
The source options that are direct members of SetupReplicationOptions should be wrapped under another structure (say for example SourceOptions) just like DestinationOptions. That distinction between source and destination will be more clear.

**Comment by sallyom** [comment]
@v-harihar if you start a PR for this, please assign to yourself, otherwise I will take care of this one in the next few days. Please assign yourself so we don't double-work. Thanks!!

**Comment by v-harihar** [comment]
@sallyom I don't have perm to assign it to my name but I am working on it and submitted the patch.
