### ISSUE TITLE
Local-path backup/restore feature

### ISSUE THREAD

**Issue by raelix** [backube/volsync#582]
**Describe the feature you'd like to have.**
Support of the local-path provisioner which is often used on bare-metal all-in-one installations .

**What is the value to the end user? (why is it a priority?)**
Allow the backup/restore for local-path provisioned volumes on small systems (kubernetes at home).

**How will we know we have a good solution? (acceptance criteria)**
- The solution should support the backup of local-path volumes 
- The solution should support the restore of local-path volumes 

**Additional context**
This could be a great feature and could be adopted by multiple users that are currently running K8s at home where there is no needed of using more powerful CSI.

**Comment by JohnStrunk** [comment]
I assume you're talking about https://github.com/rancher/local-path-provisioner?

CSI isn't strictly necessary, but it is required for the Clone or Snapshot copyMethods. In the case of non-CSI storage drivers, you should be able to use VolSync as long as you specify `copyMethod: Direct`.
As a consequence, however, you won't get a point-in-time image preserved, you'll just get the files as they exist when the data mover reads them.

**Comment by raelix** [comment]
Hi @JohnStrunk, yes I am talking about the rancher local-path-provisioner.
That's a great news! I think I should use local instead of hostPath right? Otherwise I don't think volsync will be able to attach to it. I can give it a try.

Is there an example I can follow? I'm going to use rclone to backup the data on google drive (consider that this is a simple and free solution to replicate data of small volumes e.g. home-assistant).

Thanks in advance

**Comment by JohnStrunk** [comment]
Glad you got it working!

It doesn't look like it uses CSI. You can tell what volume type it is by looking at the `.spec` of the PersistentVolume object.
Kube PV types: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes
csi is separate from both hostPath and local.

There are also solutions like [TopoLVM](https://github.com/topolvm/topolvm) that do local provisioning via CSI. But it doesn't look like that driver supports Snapshots yet.

BTW, you're braver than I am, running home assistant in kube. I stick with HassOS. 😄

**Comment by raelix** [comment]
Thanks @JohnStrunk for your suggestions :) I know how to check if it’s hostPath or local but I was mainly curious to know if there’s a way to check if it’s using CSI or not, probably checking the code to see if it’s implementing any CSI method? Thanks again!

P.S.: after deploying 2 zigbee2mqtt instances with home-assistant Supervisor using some tricks I decided to move to a better solution

**Comment by JohnStrunk** [comment]
If the volume is using CSI, the PV's `.spec.csi` will be defined instead of `.spec.local` or `.spec.hostPath`.
Also, the local-path-provisioner code doesn't import any CSI-related modules (e.g., `github.com/container-storage-interface/spec`) in their go.mod, so they don't have a CSI implementation.

Since you seem to be up-and-running, I'm going to close this issue. Feel free to re-open or create another if you run into anything else.

**Comment by raelix** [comment]
Sure thanks a lot @JohnStrunk
