### ISSUE TITLE
How do I do restic unlock command?

### ISSUE THREAD

**Issue by budimanjojo** [backube/volsync#646]
**Describe the bug**

My node got rebooted/not ready while performing backup. And now the backup job keeps failing with this in the log:
```
Defaulted container "restic" out of: restic, provide-timezone (init)
Starting container
VolSync restic container version: v0.6.0+757a700
backup prune
Testing mandatory env variables
== Checking directory for content ===
== Initialize Dir =======
unable to open cache: chtimes /cache/9f2a7056f6a71f35e0492c52ca6d4c5023f9f6342a71d2f2ae0d352cbe16723a: operation not permitted
unable to create lock in backend: repository is already locked exclusively by PID 31 on volsync-src-homeassistant-gb5xq by  (UID 0, GID 0)
lock was created at 2023-02-27 00:02:54 (8h39m47.664418473s ago)
storage ID b48b07e1
the `unlock` command can be used to remove stale locks
ERROR: failure checking existence of repository
```
**Steps to reproduce**

Forcefully remove the node while it's doing restic backup I think?

**Expected behavior**

**Actual results**

**Additional context**

**Comment by budimanjojo** [comment]
Another thing to add is the recent `do not run with root user` is causing the error 'unable to open cache` which is resulting in a very slow `prune` process. Is there anything we can do for that except for running as root user?

**Comment by JohnStrunk** [comment]
### Cache...
The 1st thing to try here is deleting the cache PVC. When the backup starts next time, it should recreate it, and it'll use the permissions that restic is running with. If that doesn't work, you may need to provide a `MoverSecurityContext` to set the Pod SecurityContext for the mover.

### Unlocking...
You'll need to unlock manually. To do that, use the same restic credentials & path as you've put into the Secret, and issue a `restic unlock` from the CLI.

**Comment by budimanjojo** [comment]
Thanks! Deleting cache PVC solved the error. Doing `restic unlock --remove-all` from CLI fixed the locking issue but I wish there's a more `kubernetes` way of this, maybe by having an annotation to do this in the `ReplicationSource` resource. Should I open a feature request for this?

**Comment by JohnStrunk** [comment]
Feel free to open an issue.  I have struggled to figure out how to handle this... It's an imperative command... "remove the existing locks" as opposed to declarative state that would be suitable for a kubernetes object.
One option would be to enhance the volsync kubectl plugin to expose the unlock command. It could retrieve the repo & creds from the cluster automatically and issue the unlock.

Glad you've got things working again!

**Comment by budimanjojo** [comment]
I've opened a feature request: https://github.com/backube/volsync/issues/653

I'll close this now. Thanks for the help!
