### ISSUE TITLE
Handling repo being stale locked for Restic based backup

### ISSUE THREAD

**Issue by budimanjojo** [backube/volsync#653]
**Describe the feature you'd like to have.**

Currently, when the `restic` replication pod got killed while performing job, the next pod will fail because the repo is still locked.
It would be nice if we can unlock the repo easily.

**What is the value to the end user? (why is it a priority?)**

It can fix jobs failing to complete because of locked repo resulting in an out of date state of the backups.

**How will we know we have a good solution? (acceptance criteria)**

Currently, the only way to remove locks is by doing `restic unlock` command manually using the CLI.
This is somewhat anti-pattern way of handling Kubernetes resources.
I am thinking about having an annotation/label for the `ReplicationSource` to instruct the operator to create a `Job` that does `restic unlock` command, something like `replicationsource.volsync.backube/remove-stale-lock: true`. Or even better we can give that annotation/label to the failing pod directly (is the operator watching for that resource?).

Another way to do this is by having `unlock` command built into the `volsync` kubectl plugin.

I'm fine with both implementations, or maybe there's better way to handle this, please do share your thought.

Thank you.

**Comment by onedr0p** [comment]
Perhaps something could be built into the kubectl plugin to help cluster admins automate this process?

**Comment by JohnStrunk** [comment]
We discussed this recently, and the current plan is to implement a solution via the ReplicationSource CR, allowing the user to indicate the desire to issue an unlock in a similar manner to how the "manual" trigger mechanism works.

### Proposal
There would be additional fields added to the `.spec` and `.status` of the RS:
```yaml
spec:
  restic:
    unlock: triggerString  #type: string
status:
  restic:
    unlock: responseString  #type: string
```

During a restic operation, if `.spec.restic.unlock` is non-empty and does not match `.status.restic.unlock`, prior to starting the backup action, a new "unlock" action would be run.
Once the Job completes, the `.status.restic.unlock` would be updated to match the string from the `.spec`.

This seems to meet the requirements for providing a way to unlock the repo (an imperative command). It doesn't require the user to install the CLI or restic locally, and they don't need to manipulate or read the restic repo Secret in the cluster.

**Comment by tesshuflower** [comment]
/assign @tesshuflower 

@JohnStrunk I was considering using `.status.restic.lastUnlocked" instead of `unlocked` just to be consistent with some of our other status fields like `lastPruned` and `lastManualSync`.

**Comment by tesshuflower** [comment]
Closing - implemented by PR #713

**Comment by billimek** [comment]
Is there appetite to extend the idea implemented in #713 further such that it doesn't still require manual intervention?

The solution, as I understand it, still requires a kubernetes operator to take the action to add the `spec.restic.unlock` field to the `ReplicationSource` object in order to facilitate recovery from a locked restic repo, unless I'm mis-understanding the situation?

**Comment by JohnStrunk** [comment]
You're correct. It does still require the user to add the unlock string to the CR. The big benefit is that the user no longer needs to install restic locally nor retrieve the access credentials from the cluster.

The reason it has been left as a manual operation is because removing valid locks could cause the repository to become corrupted. Only the user knows for sure whether they are safe to remove.

**Comment by blackjid** [comment]
Any plans to release a new version with changes??

**Comment by tesshuflower** [comment]
> Any plans to release a new version with changes??

This release has dragged on a bit, sorry for that - Our latest release date is supposed to be Nov 15 right now, but there's a chance we might be able to release earlier.
