### ISSUE TITLE
Issue with destination pod on Openshift 4.7

### ISSUE THREAD

**Issue by atanasmatev** [backube/volsync#66]
**Describe the bug**
Simple setup following the documentation. I see a destination pod is created and listening.
I create a source custom resource based on the ReplicationSource CRD and I can see the source pod starts replicating:
[amatev@ocp-installer ~]$ oc logs -f volsync-rsync-src-woof-7rhpk
VolSync rsync container version: v0.3.0
Syncing data to 172.32.156.187:22 ...

Number of files: 1 (dir: 1)
Number of created files: 0
Number of deleted files: 0
Number of regular files transferred: 0
Total file size: 0 bytes
Total transferred file size: 0 bytes
Literal data: 0 bytes
Matched data: 0 bytes
File list size: 0
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 42
Total bytes received: 19

sent 42 bytes  received 19 bytes  122.00 bytes/sec
total size is 0  speedup is 0.00
Rsync completed in 0s
Synchronization completed successfully. Notifying destination...
Initiating shutdown. Exit code: 0

When it finishes, the destination pod stops with state "Completed    0/1". Destination pod log:
VolSync rsync container version: v0.3.0
Waiting for connection...
Exiting... Exit code: 0

And then, after a new source pod is created in 5 minutes (as per the Trigger in the config), it can't connect, as there is no destination pod running.

**Steps to reproduce**

1. Create destination RSync config following: https://volsync.readthedocs.io/en/latest/usage/rsync/index.html
2. On the source, create a Secret with destnation.pub, source and source.pub from the Destination machine secret
3. Create a new Source CR

**Expected behavior**

It is expected for the destination pod (created by Job) to keep running so it can handle next rsync connection requests

**Actual results**

Destination pod stops.

**Additional context**

**Comment by JohnStrunk** [comment]
My first guess would be that there's a `.spec.trigger` defined on the destination. There shouldn't be for rsync. The schedule should only be on the source.

Assuming that's not it, could you post the source and destination yamls from your cluster (with status).

**Comment by cooktheryan** [comment]
@JohnStrunk depending on the config files I wonder if it would be worthwhile to implement a validating webhook to set specific guidelines

**Comment by atanasmatev** [comment]
No trigger on the destination. Also note that the rsync works on the first run. Then it starts acting weird when I delete the Job that activates the listener (destination) pod. On the source pod I see in the log:

VolSync rsync container version: v0.3.0
Syncing data to 172.32.156.187:22 ...
ssh: connect to host 172.32.156.187 port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.3]
Syncronization failed. Retrying in 2 seconds. Retry 1/5.
ssh: connect to host 172.32.156.187 port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.3]
Syncronization failed. Retrying in 4 seconds. Retry 2/5.
ssh: connect to host 172.32.156.187 port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.3]
Syncronization failed. Retrying in 8 seconds. Retry 3/5.
ssh: connect to host 172.32.156.187 port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.3]
Syncronization failed. Retrying in 16 seconds. Retry 4/5.
ssh: connect to host 172.32.156.187 port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.3]
Syncronization failed. Retrying in 32 seconds. Retry 5/5.

and on the destination:
VolSync rsync container version: v0.3.0
Waiting for connection...
Exiting... Exit code: 0


Also attaching the requested CRs for source and destination

`apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  creationTimestamp: '2021-08-28T12:34:23Z'
  generation: 1
  managedFields:
    - apiVersion: volsync.backube/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:rsync':
            .: {}
            'f:accessModes': {}
            'f:capacity': {}
            'f:copyMethod': {}
      manager: Mozilla
      operation: Update
      time: '2021-08-28T12:34:23Z'
    - apiVersion: volsync.backube/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
          'f:rsync':
            .: {}
            'f:address': {}
            'f:sshKeys': {}
      manager: manager
      operation: Update
      time: '2021-08-28T12:34:57Z'
  name: woof
  namespace: default
  resourceVersion: '805635'
  selfLink: >-
    /apis/volsync.backube/v1alpha1/namespaces/default/replicationdestinations/woof
  uid: 65428266-f01a-4a27-8918-be2f483a8d17
spec:
  rsync:
    accessModes:
      - ReadWriteMany
    capacity: 1Gi
    copyMethod: Snapshot
status:
  conditions:
    - lastTransitionTime: '2021-08-28T12:34:57Z'
      message: Reconcile complete
      reason: ReconcileComplete
      status: 'True'
      type: Reconciled
  rsync:
    address: 172.32.156.187
    sshKeys: volsync-rsync-dest-src-woof
`

`apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  creationTimestamp: '2021-08-28T12:40:45Z'
  generation: 1
  managedFields:
    - apiVersion: volsync.backube/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:rsync':
            .: {}
            'f:address': {}
            'f:copyMethod': {}
            'f:sshKeys': {}
          'f:sourcePVC': {}
          'f:trigger':
            .: {}
            'f:schedule': {}
      manager: Mozilla
      operation: Update
      time: '2021-08-28T12:40:45Z'
    - apiVersion: volsync.backube/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
          'f:lastSyncDuration': {}
          'f:lastSyncTime': {}
          'f:nextSyncTime': {}
          'f:rsync': {}
      manager: manager
      operation: Update
      time: '2021-08-28T12:41:03Z'
  name: woof
  namespace: default
  resourceVersion: '1813931'
  selfLink: /apis/volsync.backube/v1alpha1/namespaces/default/replicationsources/woof
  uid: 3993ba66-e600-4d94-986f-241dc958ce1d
spec:
  rsync:
    address: 172.32.156.187
    copyMethod: Clone
    sshKeys: volsync-rsync-dest-src-database-destination
  sourcePVC: volsynctest
  trigger:
    schedule: '*/5 * * * *'
status:
  conditions:
    - lastTransitionTime: '2021-08-28T13:05:00Z'
      message: Synchronization in-progress
      reason: SyncInProgress
      status: 'True'
      type: Synchronizing
    - lastTransitionTime: '2021-08-28T18:13:15Z'
      message: Reconcile complete
      reason: ReconcileComplete
      status: 'True'
      type: Reconciled
  lastSyncDuration: 1m30.048022722s
  lastSyncTime: '2021-08-28T13:01:34Z'
  nextSyncTime: '2021-08-28T13:05:00Z'
  rsync: {}
`

**Comment by JohnStrunk** [comment]
* The Source thinks the transfer finished :heavy_check_mark: 
* The Destination (pod) also thinks the transfer finished :heavy_check_mark: 

The next thing we should see on the destination is a Snapshot getting created (that happens before the Job cleanup). Since there's no `.status.latestImage` in the RD, that hasn't happened successfully.

Next things to check:
* The Job on the destination has completed successfully
* On the destination, does the temporary PVC have an annotation `volsync.backube/snapname`?
* Is there a VolumeSnapshot object in the destination namespace?
  * If so, is it bound to a VolumeSnapshotContent?
  * Is it "ready to use"?
* Perhaps check the logs from the operator and see if it's encountering any errors:
`kubectl -n volsync-system logs deploy/volsync -c manager`

Items that may be the cause of problems:
* Do you have a default VolumeSnapshotClass defined in the cluster (that is compatible with the default StorageClass on the destination)?
  * Can you manually create a snapshot of a PVC and have it bind and become ready?

**Comment by atanasmatev** [comment]
You are right. There was no default snapshot class defined. I had only default storage class. This was causing the issues. Works as a charm now.
Thanks!

**Comment by JohnStrunk** [comment]
Awesome. Glad you got it working. :100: 

/close
