### ISSUE TITLE
gh-doc: privileged movers doc missing command.

### ISSUE THREAD

**Issue by kaovilai** [backube/volsync#662]
**Describe the bug**

https://github.com/backube/volsync/blob/main/docs/usage/permissionmodel.rst#:~:text=For%20example%2C%20the%20following%20command%20will%20annotate%20a%20namespace%20to%20allow%20privileged%20movers%3A

There is no actual example commands in the link above
**Steps to reproduce**

**Expected behavior**

**Actual results**

**Additional context**

**Comment by tesshuflower** [comment]
I think this might just be a function of how github.com renders those .rst files?  If you look at the raw file, the example command and output is there in a `.. code-block:: console` section.

The fully rendered doc can be seen here:
https://volsync.readthedocs.io/en/latest/usage/permissionmodel.html

**Comment by kaovilai** [comment]
rst files with correct rendering on github can be found here. https://github.com/MarkHoeber/sublime_sphinx_guide/blob/master/source/code_blocks.rst

So I believe there is something that could be done to make it render properly

**Comment by JohnStrunk** [comment]
The documentation is meant to be rendered on readthedocs, not directly on GH. That said, if you can make it work, PRs are welcome.

**Comment by kaovilai** [comment]
testing

**Comment by kaovilai** [comment]
https://github.com/kaovilai/volsync/blob/rst-github-preview-fix-permissionmodel/docs/usage/permissionmodel.rst

looks like emphasis-lines not supported.

**Comment by kaovilai** [comment]
it does work without line highlighting. If you don't mind rephrasing the blocks such that highlighting is not required then I can make a PR.

**Comment by JohnStrunk** [comment]
That's unfortunate, but it should be ok. That particular example is pretty clear.

**Comment by kaovilai** [comment]
left feedback at https://github.com/community/community/discussions/49098

Hopefully the issue should resolve itself when its implemented.
