### ISSUE TITLE
Rclone mover doesn't appear to be able to read secrets while runAsUser

### ISSUE THREAD

**Issue by Rojikku** [backube/volsync#720]
**Describe the bug**
[Example config](https://github.com/Rojikku/home-ops/blob/bf5b4711ada5dd70a4a72cfb0d3dd7b29f296f40/cluster/apps/hass/zwave/app/volsync.yaml#L17)
I get `Failed to load config file "/rclone-config/rclone.conf": open /rclone-config/rclone.conf: permission denied` when trying to use the rclone mover

**Steps to reproduce**
Setup like example config.

Example ver of my secret file:

```
apiVersion: v1
kind: Secret
metadata:
    name: rclone-conf
    namespace: hass
stringData:
    rclone.conf: |
        [NAS]
        type = sftp
        host = 172.16.0.X
        user = backup
```

I was getting `getfacl: /data/lost+found: Permission denied` so I had to runAsUser: 1000. I don't know what it uses by default, I'd have assumed 1000.
Then, try to load the secret...you can't! Great times!
[I even tried adding root](https://github.com/Rojikku/home-ops/commit/4e98194545a37feb3f13e601f84d41f523cfbbaa) but it didn't work with the same lost+found permission denied error, when I didn't specify a runAsUser. I also got that error when I explicitly set them both as 0.

My guess is the user has to be both 1000 and 0 at the same time for this to work? Or the new privileged setup is having some issues. Or the docs are unclear?

Let me know if you need any further information, but most of it is immediately apparent in my linked repo.

Full log:
```
[volsync-rclone-src-zwave-js-ui-p64dk] VolSync rclone container version: v0.7.1+8af0bf0
[volsync-rclone-src-zwave-js-ui-p64dk] getfacl: Removing leading '/' from absolute path names
[volsync-rclone-src-zwave-js-ui-p64dk] 2023/04/21 01:37:35 DEBUG : Setting --config "/rclone-config/rclone.conf" from environment variable RCLONE_CONFIG="/rclone-config/rclone.conf"
[volsync-rclone-src-zwave-js-ui-p64dk] 2023/04/21 01:37:35 DEBUG : rclone: Version "v1.61.1" starting with parameters ["rclone" "sync" "--checksum" "--one-file-system" "--create-empty-src-dirs" "--stats" "20s" "--transfers" "10" "/data" "NAS:/k8s/zwave" "--log-level" "DEBUG"]
[volsync-rclone-src-zwave-js-ui-p64dk] 2023/04/21 01:37:35 DEBUG : Creating backend with remote "/data"
[volsync-rclone-src-zwave-js-ui-p64dk] 2023/04/21 01:37:35 Failed to load config file "/rclone-config/rclone.conf": open /rclone-config/rclone.conf: permission denied
```

Spec from ReplicationSource Describe:

```
Spec:
  Rclone:
    Copy Method:  Snapshot
    Mover Security Context:
      Run As Group:         1000
      Run As User:          1000
    Rclone Config:          rclone-conf
    Rclone Config Section:  NAS
    Rclone Dest Path:       /k8s/zwave
  Source PVC:               zwave-pvc
  Trigger:
    Schedule:  */5 * * * *
Status:
  Conditions:
    Last Transition Time:  2023-04-21T01:41:47Z
    Message:               Synchronization in-progress
    Reason:                SyncInProgress
    Status:                True
    Type:                  Synchronizing
  Last Sync Start Time:    2023-04-21T00:38:27Z
  Latest Mover Status:
    Logs:  VolSync rclone container version: v0.7.1+8af0bf0
getfacl: Removing leading '/' from absolute path names
2023/04/21 01:41:45 DEBUG : Setting --config "/rclone-config/rclone.conf" from environment variable RCLONE_CONFIG="/rclone-config/rclone.conf"
2023/04/21 01:41:45 DEBUG : rclone: Version "v1.61.1" starting with parameters ["rclone" "sync" "--checksum" "--one-file-system" "--create-empty-src-dirs" "--stats" "20s" "--transfers" "10" "/data" "NAS:/k8s/zwave" "--log-level" "DEBUG"]
2023/04/21 01:41:45 DEBUG : Creating backend with remote "/data"
2023/04/21 01:41:45 Failed to load config file "/rclone-config/rclone.conf": open /rclone-config/rclone.conf: permission denied
    Result:  Failed
Events:
  Type    Reason                        Age   From                Message
  ----    ------                        ----  ----                -------
  Normal  VolumeSnapshotCreated         63m   volsync-controller  created VolumeSnapshot/volsync-zwave-js-ui-src from PersistentVolumeClaim/zwave-pvc
  Normal  PersistentVolumeClaimCreated  63m   volsync-controller  created PersistentVolumeClaim/volsync-zwave-js-ui-src from VolumeSnapshot/volsync-zwave-js-ui-src
```

**Comment by tesshuflower** [comment]
What distribution of kubernetes are you using?

If for example you use OpenShift, then normally you shouldn't have to override the moverSecurityContext, as it will be inherited in your namespace - however this won't work in specific OpenShift built-in namespaces like `default`, `kube-system`, `kube-public`, `openshift-node`, `openshift-infra`, `openshift` as they don't assign an SCC to pods and aren't meant for running pods.

If you're on a different kubernetes distribution, most likely what you want to do is to match the moverSecurityContext to your workload that would be writing to the PVC.  You don't need to match a user id to anything in the volsync image, but instead match to the userid of your workload.  In this case it's having an issue simply mounting the secret and reading from it - so most likely related to the security context.  You may get some clues by comparing the volsync mover pod with your workload.

**Comment by Rojikku** [comment]
Going to try replying via email since I'm at work...

I'm not particularly using a distribution of Kubernetes? I'm running just
Kubernetes, 1.27.1 off the top. Using talos as the OS.

I don't really know what you mean by matching to the workload. Everything
on the PVC is owned by 1000, pretty sure the process is set to run as 1000.
So I set the mover to 1000.
The pod is created and deleted very quickly, so I don't necessarily have
the ability to check what the owner of the secret is, and from what I
understand kubernetes has no direct ability to change the owner of secrets
currently - though it's an open request.

I also think it's obviously an issue relating to the security context.
However, I don't really understand how the owner of the secret is decided,
and I don't know why it's "permission denied"- I had assumed it would be
based on your configuration of the mover when it was built.

But I don't really know what you're saying, if you're trying to say
something specific.

Are you saying the issue doesn't consistently reproduce?
Or are you saying my method of setting the runAsUser is flawed?
Or are you saying the secret is supposed to be owned by some user that the
entire workload is supposed to be running as, and I should be setting the
entire pod to do all the operations as that user so it can match the secret?

I feel like there's not sufficient documentation on the volsync page for me
to make those conclusions, currently, if the last is the issue.

**Comment by Rojikku** [comment]
> Try setting `fsGroup` in the mover security context to match the `runAsGroup` for the workload.

This made it work perfectly. Huh. I have absolutely no idea how or why that works. Thank you.
