### ISSUE TITLE
Documentation for using Volsync with Rancher

### ISSUE THREAD

**Issue by viju2008** [backube/volsync#813]
**Describe the feature you'd like to have.**

Documentation on how to use Volsync with Rancher

**What is the value to the end user? (why is it a priority?)**

Users will be able to use VolSync in Rancher Also

**How will we know we have a good solution? (acceptance criteria)**

A documentation on how to use Volsync with Rancher o

**Additional context**

**Comment by JohnStrunk** [comment]
@viju2008 Tesshu and I don't have any experience w/ Rancher
What sort of docs are you looking for? Have you tried to deploy on Rancher and run into problems?
