### ISSUE TITLE
Update restic to v0.16.2

### ISSUE THREAD

**Issue by onedr0p** [backube/volsync#957]
**Describe the feature you'd like to have.**

https://github.com/restic/restic/releases/tag/v0.16.1

**What is the value to the end user? (why is it a priority?)**

I am not sure if this applies but there is a major bugfix in this release

> In restic 0.16.0, backups where the compression level was set to max (using --compression max) could in rare and very specific circumstances result in data corruption due to a bug in the library used for compressing data.

Also this seems nice

> When running restic in a Linux container with CPU-usage limits, restic now automatically adjusts GOMAXPROCS. This helps to reduce the memory consumption on hosts with many CPU cores.

**Comment by tesshuflower** [comment]
Agreed, I just saw this became available - I'll discuss with John today if we want to pick this up and get it into the upcoming v0.8.0 release

**Comment by onedr0p** [comment]
v0.16.2 was just released

**Comment by JohnStrunk** [comment]
Fixed via #966
