### ISSUE TITLE
Unable to backup a volume after volume populator restores volume

### ISSUE THREAD

**Issue by onedr0p** [backube/volsync#981]
**Describe the bug**

@tesshuflower first off thank you so much for adding this feature, it is amazing ❤️ 

It appears the cache volume for the `ReplicationDestination` interferes with the cache volume for the `ReplicationSource` when using the Volume Populator.

**Steps to reproduce**

Deploy a `PVC` & `ReplicationDestination` and have the volume populator run on the volume. After that is done create a `ReplicationSource` that points to the same PVC.

### PVC

```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: populator-test-config
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: populator-test
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
```

### ReplicationDestination

```yaml
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: populator-test
  namespace: default
spec:
  trigger:
    manual: restore-once
  restic:
    repository: populator-test-restic-secret
    copyMethod: Snapshot
    storageClassName: ceph-block
    accessModes: ["ReadWriteOnce"]
    capacity: 1Gi
    volumeSnapshotClassName: csi-ceph-blockpool
```

### ReplicationSource

```yaml
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: populator-test
  namespace: default
spec:
  sourcePVC: populator-test-config
  trigger:
    schedule: "0 7 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: populator-test-restic-secret
    cacheCapacity: 8Gi
    cacheStorageClassName: local-path
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
      within: 3d
```

**Expected behavior**

I would expect to be able to use the Volume Populator and then have a `ReplicationSource` continue backing up the `PVC`

**Actual results**

Notice these logs in the volsync controller

```
2023-11-13T17:17:13.244-0500	ERROR	Reconciler error	{"controller": "replicationsource", "controllerGroup": "volsync.backube", "controllerKind": "ReplicationSource", "ReplicationSource": {"name":"populator-test","namespace":"default"}, "namespace": "default", "name": "populator-test", "reconcileID": "4b0b006b-1904-47c8-9f19-40d6ceae2a89", "error": "Object default/volsync-populator-test-cache is already owned by another ReplicationDestination controller populator-test"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/controller/controller.go:227
```

**Additional context**

Based on the logs it looks like the owner ref on the cache volume is interfering with letting this work:

```yaml
# k get pvc volsync-populator-test-cache -oyaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
    volume.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
  creationTimestamp: "2023-11-13T20:48:08Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/created-by: volsync
  name: volsync-populator-test-cache
  namespace: default
  ownerReferences:
  - apiVersion: volsync.backube/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationDestination
    name: populator-test
    uid: ebf5fc37-d742-4684-bd1d-dd77d6d0642d
  resourceVersion: "142328329"
  uid: 3a8c7861-91c9-4cc6-9a3e-91c992098ffd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
  volumeMode: Filesystem
  volumeName: pvc-3a8c7861-91c9-4cc6-9a3e-91c992098ffd
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
```

**Comment by onedr0p** [comment]
It's also worth noting that I am trying to do this in an automated fashion with gitops, so applying the `PVC` and `ReplicationDestination` and then deleting the cache `PVC` isn't really possible before applying the `ReplicationSource`

**Comment by onedr0p** [comment]
The workaround for this and probably the intended way is to name the `ReplicationSource` and `ReplicationDestination `differently.

I am going to close this issue unless you all think it's valid to re-open

**Comment by tesshuflower** [comment]
Glad you're liking the volumepopulator!  I think you're correct here, it's not actually volumepopulator related, but due to the fact that both replicationsource and destination for restic create the cache volume in the same way - using the replicationsource/dest name and appending "-cache" to it.  So having the same name for both in the same cluster and same namesapce is going to cause this collision.

We could consider naming the cache volume differently for src vs dest, but I'd rather not worry about orphaning existing cache volumes out there with the name change if this isn't a big issue.

**Comment by onedr0p** [comment]
@tesshuflower random question, is there any open slack community or other place to chat about volsync?

I created a volsync channel in a discord community I manage (5k+ users) as a bunch of us use this at home with our Kubernetes clusters. I'll share the discord link if you're interested in getting feedback from a ton of non-enterprise users 🙂

**Comment by tesshuflower** [comment]
@onedr0p hey that's terrific - we don't have an external slack community at the moment.  I think for now we'd prefer to keep discussions/issues in the github repo to have one location for these things.
